wandb_version: 1

experiment:
  desc: null
  value: test_hang
lr:
  desc: null
  value: 0.0001
epochs:
  desc: null
  value: 300
batch_size:
  desc: null
  value: 32
seed:
  desc: null
  value: 1
train:
  desc: null
  value:
    optimizer_cfg:
      type: optim.Adam
      params:
        lr: 0.0001
        weight_decay: 0
    scheduler_cfg:
      type: None
      params: None
    loss_cfg:
      type: nn.MSELoss
      params:
        reduction: none
    batch_size: 32
    epochs: 300
    val_freq: 10
    clip_grad: 0.5
policy:
  desc: null
  value:
    name: MLP
    act_shape:
    - 8
    nn_cfg:
      layers:
      - 256
      - 128
      activation: nn.ReLU
      normalization: None
      final_act: false
      zero_init_output: true
    head_cfg:
      act_bounds:
      - - -1
        - -1
        - -1
        - -1
        - -1
        - -1
        - -1
        - 0
      - - 1
        - 1
        - 1
        - 1
        - 1
        - 1
        - 1
        - 1
      std: 1.0e-06
    device: cuda
train_dataset:
  desc: null
  value:
    folders:
    - /data/dataset/0414_red_bag_hang_s/t/
    obs_shapes:
      rgb:
      - 3
      - 224
      - 224
      depth:
      - 1
      - 224
      - 224
      state:
      - 7
    act_shape:
    - 8
    act_bounds:
    - - -1
      - -1
      - -1
      - -1
      - -1
      - -1
      - -1
      - 0
    - - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
    loader_cfg:
      batch_size: 32
      num_workers: 8
    aug_cfg:
      rgb_aug: false
      num_frames: 4
      stack_idx:
      - 0
      - 1
      - 2
      - 3
      use_proprio: true
    token_name: none
val_dataset:
  desc: null
  value:
    folders:
    - /data/dataset/0414_red_bag_hang_s/v/
    obs_shapes:
      rgb:
      - 3
      - 224
      - 224
      depth:
      - 1
      - 224
      - 224
      state:
      - 7
    act_shape:
    - 8
    act_bounds:
    - - -1
      - -1
      - -1
      - -1
      - -1
      - -1
      - -1
      - 0
    - - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
    loader_cfg:
      batch_size: 32
      num_workers: 2
    aug_cfg:
      rgb_aug: false
      num_frames: 4
      stack_idx:
      - 0
      - 1
      - 2
      - 3
      use_proprio: true
    token_name: none
encoder:
  desc: null
  value:
    name: IMPALA
    obs_shapes:
      rgb:
      - 3
      - 224
      - 224
      depth:
      - 1
      - 224
      - 224
      state:
      - 7
    num_frames: 4
    out_shape: 384
    nn_cfg:
      shape:
      - 224
      - 224
      in_channels: 16
    device: cuda
gpu:
  desc: null
  value: null
wandb:
  desc: null
  value:
    project: internet-manipulation
    entity: johnrso
    name: 2023.04.14_1507_test_hang_IMPALA_MLP
    group: test_hang_IMPALA_MLP
_wandb:
  desc: null
  value:
    python_version: 3.9.0
    cli_version: 0.14.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1681510033.185886
    t:
      1:
      - 1
      - 41
      - 49
      - 50
      - 55
      - 63
      2:
      - 1
      - 41
      - 49
      - 50
      - 55
      - 63
      3:
      - 13
      - 16
      - 23
      4: 3.9.0
      5: 0.14.2
      8:
      - 5
